# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'
 
steps:
- task: Maven@3
  displayName: 'Maven pom.xml'
  inputs:
    options: '-DskipITs --settings ./maven/settings.xml'

    publishJUnitResults: false

