# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    yarn global add react-static
  displayName: 'yarn global add react-static'

- script: |
    yarn add --dev @babel/preset-flow
  displayName: 'yarn add --dev @babel/preset-flow'

- script: |
    yarn deploy
  displayName: 'yarn deploy'

